"""Shared fixtures.

Two rules the whole suite obeys:

* **No API money.** Every test injects a fake client; nothing here can reach OpenRouter.
* **No v1 text.** The fake v1 checkout below is written by us. Its man pages and specs are
  invented for testing, so nothing from v1's private repo enters this repository, and the
  suite passes on a machine with no v1 checkout at all.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

from caruca_v2 import v1

# Enough of a spec to import cleanly and define the reflectively-required binding, with
# no dependency on v1's DSL module.
FAKE_SPEC_TEMPLATE = """\
{command}_syntax_spec = [
    [
        [("-a",), ("-b",)],
        [("PATH",)],
    ]
]
"""

FAKE_MAN_TEMPLATE = """\
{upper}(1)

NAME
       {command} - a fabricated command used only by the caruca_v2 test suite

SYNOPSIS
       {command} [OPTION]... PATH...

DESCRIPTION
       -a, --alpha
              the first fabricated option

       -b, --beta
              the second fabricated option
"""


def _write_command(package_root: Path, command: str) -> None:
    slug = v1.slug(command)
    (package_root / "doc_sources" / "man" / f"{slug}.txt").write_text(
        FAKE_MAN_TEMPLATE.format(command=command, upper=slug.upper())
    )
    (package_root / "syntax_specs" / f"{slug}.py").write_text(
        FAKE_SPEC_TEMPLATE.format(command=slug)
    )



# A miniature stand-in for the parts of v1's package the boundary module reaches into:
# the DSL's value types (for the probe table) and `CommandConfig` (for config validation).
# Small on purpose — it exists to make the subprocess boundary real, not to reimplement v1.
FAKE_PACKAGE_FILES = {
    "caruca/__init__.py": "",
    "caruca/ir/__init__.py": "",
    "caruca/ir/syntax.py": """
class ValueArgument:
    elaborate_relations = False

    def syntax(self):
        return []


class Glob(ValueArgument):
    def syntax(self):
        return ["*.txt", "*.py"]


class Signal(ValueArgument):
    def syntax(self):
        return ["HUP", "INT"]


class Path(ValueArgument):
    def syntax(self):
        return ["relpath_1", "abspath_1"]


class Unconstructable(ValueArgument):
    def __init__(self, required):
        self.required = required
""",
    "caruca/ir/environment.py": """
from enum import Enum
from pathlib import Path
from typing import Annotated

from pydantic import BaseModel, PlainSerializer, PlainValidator, computed_field


class Content(Enum):
    HUMAN_TEXT = b"standard input\\n"

    @classmethod
    def deserialize(cls, item):
        return item if isinstance(item, cls) else cls[item]


SerializableContent = Annotated[
    Content,
    PlainSerializer(lambda c: c.name, return_type=str),
    PlainValidator(Content.deserialize),
]


class ArgumentSequenceWithEnv(BaseModel):
    flag: str | None = None
    args: list[str] = []

    def prepare(self, sandbox):
        for name in self.args:
            (Path(sandbox) / name).write_text("fixture\\n")


class CommandConfig(BaseModel):
    name: str
    body: list[ArgumentSequenceWithEnv] = []
    string: dict = {}
    stdin: SerializableContent = Content.HUMAN_TEXT

    @computed_field
    @property
    def true_string(self) -> str:
        parts = [self.name]
        for sequence in self.body:
            if sequence.flag:
                parts.append(sequence.flag)
            parts.extend(sequence.args)
        return " ".join(parts)
""",
    "caruca/annotator/__init__.py": """
from pydantic import BaseModel, RootModel


class PaShCase(BaseModel):
    predicate: dict | str
    pclass: str
    inputs: list[str] = []
    outputs: list[str] = []
    true_str: str


class PaSh(BaseModel):
    command: str
    cases: list[PaShCase]


class Posh(BaseModel):
    command: str
    cases: list[dict]


SaSh = RootModel[list[dict]]


def render_shellcheck_module(command, cases, missing_destination=None):
    return (
        f"-- Generated by caruca.\\n-- Command: {command}\\n"
        "module Caruca.DangerousDelete where\\n\\ndeletePatterns = [ ]\\n"
    )
""",
    "caruca/tracer/__init__.py": "",
    "caruca/tracer/data.py": """
from enum import Enum
from pathlib import Path
from typing import Literal, TypeAlias

from pydantic import BaseModel, RootModel

from caruca.ir.environment import CommandConfig


class FSInteraction(Enum):
    REPLACED_WITH_DIRECTORY = "rd"
    CREATED_DIRECTORY = "md"
    MODIFIED_FILE = "mo"
    DELETED_FILE = "de"
    CREATED_FILE = "ad"
    READ_FILE = "rf"
    WRITTEN_FILE = "wf"


Trace: TypeAlias = tuple[FSInteraction, Path | Literal["stdin", "stdout", "stderr"]]


class CommandInvocationTraces(BaseModel):
    command: CommandConfig
    return_code: int | None
    stdout: str | None
    stderr: str | None
    traces: list[Trace]


class CommandInvocationTraceSet(BaseModel):
    command: dict
    true_str: str
    configs: list[CommandInvocationTraces]


Traces = RootModel[list[CommandInvocationTraceSet]]
""",
}

# Stands in for `caruca generate CMD`. Deliberately returns a small, fixed set so the
# set-diff in the tests has a known answer.
FAKE_TRACES = [
    {
        "command": {"name": "mkdir", "body": []},
        "true_str": "mkdir relpath_1",
        "configs": [
            {
                "command": {"name": "mkdir", "body": [], "string": {}, "stdin": "HUMAN_TEXT"},
                "return_code": 0,
                "stdout": "",
                "stderr": "",
                "traces": [["md", "relpath_1"]],
            }
        ],
    }
]

FAKE_CARUCA_INVOCATIONS = ["mkdir relpath_1", "mkdir abspath_1", "mkdir -p relpath_1"]

FAKE_CARUCA_SCRIPT = """#!/bin/sh
case "$1" in
  annotate)
    cat "{annotation_file}"
    exit 0
    ;;
esac
for arg in "$@"; do
  if [ "$arg" = "--number" ]; then
    echo {hint}
    exit 0
  fi
done
{echoes}
"""

# What the fake v1 annotator "produces", and what the hand-curated ground truth holds.
# They differ by one case so the two diffs in the manifest cannot be confused for each other.
FAKE_V1_ANNOTATION = {
    "command": "mkdir",
    "cases": [
        {"predicate": "default", "pclass": "stateless", "inputs": [], "outputs": ["stdout"],
         "true_str": "mkdir relpath_1"}
    ],
}
FAKE_GROUND_TRUTH_ANNOTATION = {
    "command": "mkdir",
    "cases": [
        {"predicate": "default", "pclass": "side-effectful", "inputs": [],
         "outputs": ["stdout"], "true_str": "mkdir relpath_1"}
    ],
}


def _write_fake_package(root: Path) -> Path:
    package_dir = root / "fake_site_packages"
    for relative, source in FAKE_PACKAGE_FILES.items():
        path = package_dir / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source)
    return package_dir


def _write_fake_venv(root: Path) -> None:
    venv_bin = root / "caruca" / ".venv" / "bin"
    venv_bin.mkdir(parents=True)

    python = venv_bin / "python"
    python.write_text(
        f'#!/bin/sh\nPYTHONPATH="{root / "fake_site_packages"}" exec "{sys.executable}" "$@"\n'
    )
    python.chmod(0o755)

    annotation_file = root / "fake_v1_annotation.json"
    annotation_file.write_text(json.dumps(FAKE_V1_ANNOTATION, indent=1) + "\n")

    caruca = venv_bin / "caruca"
    echoes = "\n".join(f'echo "{line}"' for line in FAKE_CARUCA_INVOCATIONS)
    # The hint deliberately disagrees with the line count, as v1's own does.
    caruca.write_text(
        FAKE_CARUCA_SCRIPT.format(hint=99, echoes=echoes, annotation_file=annotation_file)
    )
    caruca.chmod(0o755)

@pytest.fixture
def fake_v1_root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A minimal stand-in for the v1 checkout, pointed at by CARUCA_V1_ROOT.

    Its `.venv/bin/python` is a shell wrapper around the interpreter running the tests,
    with a miniature `caruca` package on the path. The subprocess boundary is therefore
    genuinely exercised — the same code path production uses — without needing the real,
    private v1 checkout to be present.
    """
    root = tmp_path / "caruca_v1"
    package_root = root / "caruca" / "src" / "caruca"
    (package_root / "doc_sources" / "man").mkdir(parents=True)
    (package_root / "syntax_specs").mkdir(parents=True)
    (package_root / "data").mkdir(parents=True)

    for command in (*v1.EXEMPLAR_COMMANDS, "mkdir", "git commit"):
        _write_command(package_root, command)

    _write_fake_package(root)
    _write_fake_venv(root)

    outputs = root / "caruca" / "outputs"
    outputs.mkdir(parents=True)
    (outputs / "mkdir.json").write_text(json.dumps(FAKE_TRACES, indent=1) + "\n")

    ground_truth = root / "benchmarks" / "annotations" / "pash"
    ground_truth.mkdir(parents=True)
    (ground_truth / "mkdir.json").write_text(
        json.dumps(FAKE_GROUND_TRUTH_ANNOTATION, indent=1) + "\n"
    )

    monkeypatch.setenv("CARUCA_V1_ROOT", str(root))
    return root


@pytest.fixture
def valid_spec_response() -> str:
    """A model response in the shape the prompt asks for: prose, then one fenced block."""
    return (
        "Looking at the documentation, mkdir takes two flags and at least one path.\n\n"
        "```python\n" + FAKE_SPEC_TEMPLATE.format(command="mkdir") + "```\n"
    )


@pytest.fixture(autouse=True)
def no_real_api_key(monkeypatch: pytest.MonkeyPatch) -> None:
    """Guarantee a stray real key in the developer's environment is never used."""
    monkeypatch.delenv("CARUCA_V2_LOG_CONVERSATION", raising=False)
    monkeypatch.setenv("OPENROUTER_API_KEY", "test-key-not-real")
