/**
 * A small Markdown renderer for the drill-down sections.
 *
 * Deliberately not a library. These documents are generated by `scripts/parity_diff.py` and
 * use a narrow subset - headings, bullets, fenced code, bold, inline code - so a renderer that
 * handles exactly that subset is smaller than the dependency and cannot surprise us.
 *
 * **Nothing is rendered as HTML.** The documents quote v1's source and the two systems' raw
 * output verbatim, which means they contain arbitrary text; every piece of it reaches the page
 * as a React text node, so it is escaped by construction and no markup in the data can become
 * markup on the page.
 */
import type { ReactNode } from "react";

/** `**bold**` and `` `code` ``, applied to a plain string. */
function inline(text: string, keyPrefix: string): ReactNode[] {
  const out: ReactNode[] = [];
  // `[[id]]` is how findings cross-reference each other, following the convention the
  // project's memory notes already use. A link to a finding that does not exist yet is fine:
  // it marks something worth writing, which is what the convention is for.
  const pattern = /(\*\*[^*]+\*\*|`[^`]+`|\[\[[^\]]+\]\])/g;
  let last = 0;
  let match: RegExpExecArray | null;
  let index = 0;

  while ((match = pattern.exec(text)) !== null) {
    if (match.index > last) out.push(text.slice(last, match.index));
    const token = match[0];
    if (token.startsWith("[[")) {
      const id = token.slice(2, -2);
      out.push(
        <a key={`${keyPrefix}-w${index}`} href={`#${id}`} className="mono">
          {id}
        </a>,
      );
    } else if (token.startsWith("**")) {
      out.push(
        <strong key={`${keyPrefix}-b${index}`} style={{ fontWeight: "var(--weight-semibold)" }}>
          {token.slice(2, -2)}
        </strong>,
      );
    } else {
      out.push(
        <code key={`${keyPrefix}-c${index}`} className="code-inline">
          {token.slice(1, -1)}
        </code>,
      );
    }
    last = match.index + token.length;
    index += 1;
  }
  if (last < text.length) out.push(text.slice(last));
  return out;
}

export function Markdown({ source }: { source: string }) {
  const blocks: ReactNode[] = [];
  const lines = source.split("\n");
  let index = 0;
  let key = 0;

  while (index < lines.length) {
    const line = lines[index]!;

    // Fenced code, including the `diff` blocks the parity diffs use.
    if (line.startsWith("```")) {
      const language = line.slice(3).trim();
      const body: string[] = [];
      index += 1;
      while (index < lines.length && !lines[index]!.startsWith("```")) {
        body.push(lines[index]!);
        index += 1;
      }
      index += 1;
      blocks.push(
        <pre key={key++} className="codeblock mono">
          {language === "diff"
            ? body.map((row, rowIndex) => (
                <div
                  key={rowIndex}
                  style={{
                    color: row.startsWith("+")
                      ? "var(--success-text)"
                      : row.startsWith("-")
                        ? "var(--danger-text)"
                        : undefined,
                  }}
                >
                  {row || " "}
                </div>
              ))
            : body.join("\n")}
        </pre>,
      );
      continue;
    }

    if (line.startsWith("### ")) {
      blocks.push(
        <div key={key++} className="label" style={{ marginTop: 14, marginBottom: 6 }}>
          {line.slice(4)}
        </div>,
      );
      index += 1;
      continue;
    }

    if (/^\s*[*-] /.test(line)) {
      const items: string[] = [];
      while (index < lines.length && /^\s*[*-] /.test(lines[index]!)) {
        items.push(lines[index]!.replace(/^\s*[*-] /, ""));
        index += 1;
      }
      blocks.push(
        <ul key={key++} style={{ margin: "6px 0", paddingLeft: 20, fontSize: "var(--text-small)" }}>
          {items.map((item, itemIndex) => (
            <li key={itemIndex} style={{ marginBottom: 2 }}>
              {inline(item, `${key}-${itemIndex}`)}
            </li>
          ))}
        </ul>,
      );
      continue;
    }

    if (line.trim() === "" || line.trim() === "---") {
      index += 1;
      continue;
    }

    const paragraph: string[] = [];
    while (
      index < lines.length &&
      lines[index]!.trim() !== "" &&
      !lines[index]!.startsWith("```") &&
      !lines[index]!.startsWith("#") &&
      !/^\s*[*-] /.test(lines[index]!)
    ) {
      paragraph.push(lines[index]!);
      index += 1;
    }
    blocks.push(
      <p key={key++} style={{ margin: "6px 0", fontSize: "var(--text-small)" }}>
        {inline(paragraph.join(" "), String(key))}
      </p>,
    );
  }

  return <>{blocks}</>;
}
